<?php

// Enables page callback
function calculate_menu()
{
	$urls = array();
	$urls['calculate/form'] = array(
		'type' 				=> MENU_CALLBACK,
		'page callback' 	=> 'drupal_get_form',
		'page arguments' 	=> array('calculate_my_form'),
		'access arguments' 	=> array('access content'),
		'title' 			=> t('Add me'),
	);
	return $urls;
}

// Creating a form

function calculate_form() {
	return drupal_get_form('calculate_my_form');
}

function calculate_my_form($form_state) {
	$form = array();

	$form['first_number'] = array(
		'#type' 	=> 'textfield',
		'#title' 	=> t('Enter a number ')
	);

	$form['second_number'] = array(
		'#type' 	=> 'textfield',
		'#title' 	=> t('Enter another number ')
	);

	$form['submit'] = array(
		'#type' 	=> 'submit',
		'#value' 	=> 'Submit',
		'#title' 	=> t('Submit')
	);

	return $form;
}

function drupalform_my_form_validate($form, $form_state) {
	if(empty($form_state['values']['first_number']))
		form_set_error('first_number', 'First number cannot be empty');
	else if(empty($form_state['values']['second_number']))
		form_set_error('second_number', 'Second number cannot be empty');
}

function drupalform_my_form_submit($form, $form_state) {
	drupal_set_message("Form has been submitted");
}

// Creates calculate/add_me page -- test that module created an element
// function calculate_me()
// {
// 	$display = array();
// 	$display["element"] = array(
// 		"#tag" => "h1",
// 		"#value" => "I will turn into a calculating form soon..."
// 	);
// 	return theme_html_tag($display);	
// }

